image: maven:latest
#inspired by https://gitlab.com/gitlab-examples/maven/simple-maven-example
cache:
  paths:
    - .m2/repository/
    - target/

Build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

Time-IP-Filter:
  stage: test
  script:
    - mvn -Dtest=Aufgabe1Test test

Halstead-Task:
  stage: test
  script:
    - mvn -Dtest=Aufgabe2Test test

SyntaxErkenner-Task1:
  stage: test
  script:
    - mvn -Dtest=Aufgabe3Test$testAufgabe1 test

SyntaxErkenner-Task2:
  stage: test
  script:
    - mvn -Dtest=Aufgabe3Test$testAufgabe2 test

SyntaxErkenner-Task3:
  stage: test
  script:
    - mvn -Dtest=Aufgabe3Test$testAufgabe3 test

Interpreter-Task2:
  stage: test
  script:
    - mvn -Dtest=Aufgabe4Test$testAufgabe2 test

Interpreter-Task3:
  stage: test
  script:
    - mvn -Dtest=Aufgabe4Test$testAufgabe3 test

Interpreter-Task4:
  stage: test
  script:
    - mvn -Dtest=Aufgabe4Test$testAufgabe4 test

CallGraph-Task2:
  stage: test
  script:
    - mvn -Dtest=Aufgabe5Test$testAufgabe2 test


deploy-prod:
  stage: deploy
  script:
    - echo "We don´t need this here"